version: '3.8'

services:
  backend:
    image: vimukthiserasinghe/todo-backend:latest
    container_name: todo_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      mysql_db:
        condition: service_healthy

  frontend:
    image: vimukthiserasinghe/todo-frontend:latest
    container_name: todo_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started

  mysql_db:
    image: mysql:8.0
    container_name: todo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: todotasks
    volumes:
      - todo_data:/var/lib/mysql
      - ./todotasks.sql:/docker-entrypoint-initdb.d/todotasks.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  todo_data:
